### ISSUE TITLE
事例研究IIIdescriptionの表示

### ISSUE THREAD

**Issue by KazukiHiraizumi** [CA-Giken/eel-example#3]
JSで書くのではなく、様式を決めること。

**Comment by KazukiHiraizumi** [comment]
様式案1
&lt;div class="description" file="descrition.csv"&gt;
  &lt;div bind="threshold input:0" key="threshold label:0" /&gt;     //name="threshold"の子要素にバインド、キー取得
  &lt;div bind="threshold input:1" key="threshold label:1" /&gt;
  &lt;div bind="threshold input:2" key="threshold label:2" /&gt;
&lt;/div&gt;

**Comment by KazukiHiraizumi** [comment]
様式案2
セレクト時にdescriptionイベントを発行する
~~~
{% with name="/thresholding/method", value="fixed", id="thre-fixed-radio" , emit="description" %}
  {% include "components/params/StringRadio.html" %}
{% endwith %}
~~~
descritionクラスがキャッチする
~~~
<div class="description" file="descrition.csv">
</div>
~~~

**Comment by HiraiKyo** [comment]
https://github.com/CA-Giken/eel-ros1/issues/4
- optional attrは全てoptions=に入れる。
- イベント発行は、onClick, onSelect, onMouseOver, onMouseLeave, 
- on-* はオーバーライドではなく結合とする
- 複数イベント発行はスペース区切りとする
- CSVデータへの参照は、`data-row-id`を行ID `data-column`を列名とする

# 表示側
```
<div class="description" file="descrition.csv">
  <p class="description-title"></p>
  <p class="description-text"></p>
</div>
```

# 表示切替イベント側
```
{% with name="/thresholding/method", value="fixed", id="thre-fixed-radio" , options={"onMouseOver": "description", "onSelect": "description highlight", "onMouseLeave": "description-clear", data-id="/params/thresholding/method/fixed" } %}
  {% include "components/params/StringRadio.html" %}
{% endwith %}
```

**Comment by HiraiKyo** [comment]
個別レポジトリに記帳したためクローズ
